{
    "code": 0,
    "msg": "ok",
    "data": [{
        "role": 'teacher',
        "menu": [{
            "name": '首页',
            "path": '/',
        }, {
            "name": '课程管理',
            "path": '/course/index',
        }, {
            "name": '开课管理',
            "path": '/techmanage/index',
        }, {
            "name": '实验管理',
            "path": '/experiment/mylist',
        }, {
            "name": '资源管理',
            "path": '/sourcemanage/mylist',
        }, {
            "name": '题库管理',
            "path": '/examine/knownledge',
        }, {
            "name": '课程表',
            "path": '/',
        }, {
            "name": '答疑室',
            "path": '/',
        }, {
            "name": '个人信息',
            "path": '/',
        }]
    }, {
        "role": 'student',
        "menu": [{
            "name": '首页',
            "path": '/student'
        }, {
            "name": '选课',
            "path": '/checkcourse/preintro'
        }, {
            "name": '资源库',
            "path": '/'
        }, {
            "name": '课程表',
            "path": '/'
        }, {
            "name": '答疑室',
            "path": '/'
        }, {
            "name": '个人信息',
            "path": '/'
        }]
    }, {
        "role": 'admin',
        "menu": [{
            "name": '用户管理',
            "path": '/'
        }, {
            "name": '系统管理',
            "path": '/'
        }, {
            "name": '学期配置',
            "path": '/'
        }, {
            "name": '统计管理',
            "path": '/'
        }, {
            "name": '个人信息',
            "path": '/'
        }]
    }]
}